version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/maven
  maven: circleci/maven@1.4.1

executors:
  openjdk17:
    docker:
      # https://circleci.com/developer/ja/images/image/cimg/openjdk
      - image: cimg/openjdk:17.0

workflows:
  verify:
    jobs:
      - maven/test:
          name: test
          executor: openjdk17
