spring:
  application:
    name: producer
  main:
    banner-mode: off
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: sample
          content-type: text/plain

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  tracing:
    baggage:
      remote-fields:
        - sample-msg-process-time-millis

logging:
  level:
    root: info
    org.apache.tomcat: warn
    org.apache.catalina: warn
    org.springframework: warn
